# My First Notebook

In [1]:
print('Hello world!')

Hello world!


In [37]:
x='python' #define a variable x

In [38]:
print(x)

python


In [5]:
x

'python'

In [40]:
print(x + ' review')

python review


In [7]:
print(x + 4)

TypeError: can only concatenate str (not "int") to str

In [8]:
print('Testing: {one}, {two}'.format(one=x, two=4))

Testing: python, 4


In [11]:
print('{}, {}'.format(x, 4))

python, 4


In [1]:
[1, 2, 3]

[1, 2, 3]

In [4]:
['hello', 2, [3, 4]]

['hello', 2, [3, 4]]

In [3]:
myList = [1, 2, 3]
myList.append('d')
print(myList)

[1, 2, 3, 'd']


In [5]:
myList[2]

3

In [6]:
myList[2:]

[3, 'd']

In [7]:
myList[:2]

[1, 2]

In [8]:
myList[0] ='a'

In [9]:
print(myList)

['a', 2, 3, 'd']


<h2>Dictionaries</h2>

In [12]:
di={'key1':'value1', 'key2':5}
di['key1']

'value1'

<h2>Sets</h2>

In [10]:
{1, 2, 3}

{1, 2, 3}

In [11]:
{1, 2, 3, 3, 3, 2, 1, 3, 3, 1, 1}

{1, 2, 3}

<h2>Comparison Operators</h2>

In [13]:
1>2

False

In [12]:
1<2

True

In [15]:
(1<2) and (1>2)

False

In [16]:
(1<2) or (1>2)

True

In [ ]:
if 1>2:
    print('a')
elif 1==2:
    print('b')
elif 2==2:
    print('c')
else:
    print('d')

In [ ]:
i = 1
while i <= 5:
    print('i is: {}'.format(i))

# Functions

In [1]:
def my_function(param1, param2='default'):
    print('param1 is: {}'.format(param1))
    print('param2 is: {}'.format(param2))

In [2]:
my_function(4)

param1 is: 4
param2 is: default


In [3]:
my_function(4, 5)

param1 is: 4
param2 is: 5


In [ ]:
def prog_tax(salary=0):
    if salary <=40000:
        return '${:.2f}'.format(salary*0.20)
    elif salary <=100000:
        return '${:.2f}'.format(8000+((salary-40000)*0.30))
    elif salary >100000:
        return '${:.2f}'.format(26000+((salary-100000)*0.40))
    else:
        return "could not calculate"

In [ ]:
prog_tax(63133)

# NumPy

In [1]:
import numpy as np

#from a list
array_from_list = np.array([1, 2, 3, 4])
print(array_from_list)

#using zeroes
zeros_array = np.zeros((2, 3))
print(zeros_array)

[1 2 3 4]
[[0. 0. 0.]
 [0. 0. 0.]]


In [2]:
array = np.array([1, 2, 3, 4, 5])
print(array[0])
print(array[1:4])
print(array + 1)
print(array * 2)

1
[2 3 4]
[2 3 4 5 6]
[ 2  4  6  8 10]


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

# Mathematical operations

In [ ]:
matrix = np.array([1, 2], [3, 4])
determinant = np.linalg.det(matrix)
print(determinant)

In [3]:
import numpy as np

print(np.__version__)

1.26.4


In [ ]:
newList = [1, 2, 3]
np.array(newList)

In [ ]:
np.arrange(0, 10)

In [ ]:
np.arrange(0 , 11, 2)

In [ ]:
np.random.rand(10)

In [ ]:
np.random.rand(10)*10

In [ ]:
np.random.rand(4, 4)

In [ ]:
np.random.randint(1, 100, 10)

In [ ]:
myIntArray = np.random.randint(1, 100, 10)
myIntArray

In [ ]:
myIntArray.max()
myIntArray.argmax()
myIntArray.min()
myIntArray.argmin()
myIntArray[3]
myIntArray[2:5]

# Pandas

In [ ]:
import numpy as np
import pandas as pd

labels = ['a', 'b', 'c']
values = [7,8,9]
dictionary = {'a':7, 'b':8, 'c':9}

In [ ]:
pd.Series(data=values, index=labels)

In [ ]:
pd.Series(dictionary)

In [ ]:
set1 = pd.Series(data=values, index=labels)
set2 = pd.Series(dictionary)
set3 = set1 + set2
set3

# Dataframe

In [ ]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)
print(df)

In [ ]:
import pandas as pd

data = [
    ['Alice', 25, 'New York'],
    ['Bob', 30, 'Los Angeles'],
    ['Charlie', 35, 'Chicago']
]

columns = ['Name', 'Age', 'City']

df = pd.DataFrame(data, columns=columns)

print(df)

In [ ]:
print(df.iloc[0])
print(df.loc[0])

# CSV files

In [ ]:
df = pd.read_csv('data.csv')

print(df['Name'])

print(df[df['Age'] > 25])

df['Salary'] = [70000, 80000, 90000]
print(df)

grouped = df.groupby('City')
print(grouped['Age'].mean())

df.fillna(0, inplace=True)

df.dropna(inplace=True)

In [11]:
import numpy as np
import pandas as pd

labels_new = ['a', 'b', 'c']
values1= np.random.rand(20, 4)
values2= np.random.rand(20, 4)
values3= np.random.rand(20, 4)
cols = ['W', 'X', 'Y', 'Z']

multiArray = [values1.tolist(), values2.tolist(), values3.tolist()]

flattened_multiArr = [item for sublist in multiArray for item in sublist]

dataFrame = pd.DataFrame(data=flattened_multiArr, columns=cols)

dataFrame

W         X         Y         Z
0   0.053658  0.891749  0.136886  0.676516
1   0.517299  0.730383  0.950864  0.833559
2   0.736789  0.144842  0.869749  0.368362
3   0.253387  0.960268  0.298020  0.731131
4   0.474302  0.995580  0.263277  0.260873
5   0.843857  0.241197  0.756605  0.845783
6   0.156269  0.260637  0.340815  0.907928
7   0.082069  0.062995  0.733348  0.920766
8   0.865808  0.278034  0.640922  0.905490
9   0.344353  0.884663  0.309399  0.990720
10  0.651813  0.704361  0.078532  0.574190
11  0.485596  0.360519  0.553330  0.578550
12  0.580343  0.865760  0.967075  0.894048
13  0.760117  0.265385  0.502313  0.774096
14  0.843083  0.635828  0.317488  0.042874
15  0.766730  0.263869  0.705161  0.242770
16  0.222220  0.229465  0.177108  0.941769
17  0.825229  0.470504  0.216519  0.914694
18  0.761745  0.356599  0.806759  0.743189
19  0.922617  0.477434  0.897377  0.511959
20  0.001975  0.502431  0.166829  0.125512
21  0.836974  0.847921  0.773648  0.689553
22  0.991447  0.461161  0.914051  0.608499
23  0.448993  0.646557  0.308037  0.948134
24  0.012724  0.666883  0.541361  0.237506
25  0.829838  0.962669  0.163872  0.430188
26  0.817607  0.733099  0.389853  0.055736
27  0.413990  0.335205  0.696372  0.537457
28  0.449147  0.712366  0.837584  0.865491
29  0.882496  0.726720  0.159526  0.165009
30  0.767419  0.499641  0.312184  0.809598
31  0.890904  0.497236  0.402776  0.740486
32  0.660386  0.415972  0.897048  0.586005
33  0.703361  0.295038  0.254929  0.441209
34  0.652174  0.161277  0.762802  0.910206
35  0.255551  0.369938  0.018456  0.467304
36  0.135217  0.054327  0.849746  0.887221
37  0.330568  0.001420  0.223759  0.694910
38  0.155786  0.215030  0.330776  0.171014
39  0.583149  0.618692  0.159309  0.885062
40  0.072486  0.597401  0.582325  0.218382
41  0.127474  0.739164  0.506288  0.764206
42  0.725750  0.816711  0.205093  0.950634
43  0.222784  0.530855  0.995143  0.618674
44  0.332305  0.356187  0.800483  0.244643
45  0.008958  0.131560  0.501106  0.597667
46  0.995970  0.616158  0.975938  0.058336
47  0.625642  0.742597  0.183395  0.398057
48  0.533047  0.562315  0.951345  0.028779
49  0.136809  0.679218  0.752385  0.552021
50  0.824284  0.970517  0.063607  0.056930
51  0.401758  0.963311  0.043783  0.081545
52  0.405278  0.010577  0.783277  0.832287
53  0.030920  0.608325  0.562303  0.691980
54  0.531890  0.432852  0.323168  0.026014
55  0.591129  0.752152  0.144067  0.975281
56  0.347152  0.787107  0.571696  0.441340
57  0.944629  0.411152  0.880483  0.176047
58  0.469072  0.678394  0.017266  0.461286
59  0.207766  0.113678  0.666941  0.359070

In [6]:
dataFrame.Z

0     0.033871
1     0.234117
2     0.658057
3     0.102395
4     0.960586
5     0.557825
6     0.510174
7     0.387592
8     0.569505
9     0.901920
10    0.672201
11    0.161833
12    0.777435
13    0.897034
14    0.380705
15    0.356073
16    0.407064
17    0.967735
18    0.162435
19    0.134923
20    0.583264
21    0.740103
22    0.902113
23    0.789273
24    0.239025
25    0.951637
26    0.261502
27    0.705669
28    0.391412
29    0.462124
30    0.530460
31    0.144810
32    0.715732
33    0.978949
34    0.266243
35    0.785182
36    0.186610
37    0.174626
38    0.079321
39    0.285359
40    0.049903
41    0.942222
42    0.305998
43    0.679230
44    0.373074
45    0.882096
46    0.126105
47    0.242488
48    0.349705
49    0.172598
50    0.514872
51    0.368563
52    0.935794
53    0.565117
54    0.463958
55    0.928003
56    0.358545
57    0.087231
58    0.791067
59    0.225293
Name: Z, dtype: float64

In [12]:
dataFrame['Sum(X+Y)'] = dataFrame['X'] + dataFrame['Y']
dataFrame

W         X         Y         Z  Sum(X+Y)
0   0.053658  0.891749  0.136886  0.676516  1.028635
1   0.517299  0.730383  0.950864  0.833559  1.681248
2   0.736789  0.144842  0.869749  0.368362  1.014591
3   0.253387  0.960268  0.298020  0.731131  1.258288
4   0.474302  0.995580  0.263277  0.260873  1.258858
5   0.843857  0.241197  0.756605  0.845783  0.997802
6   0.156269  0.260637  0.340815  0.907928  0.601453
7   0.082069  0.062995  0.733348  0.920766  0.796342
8   0.865808  0.278034  0.640922  0.905490  0.918955
9   0.344353  0.884663  0.309399  0.990720  1.194062
10  0.651813  0.704361  0.078532  0.574190  0.782893
11  0.485596  0.360519  0.553330  0.578550  0.913849
12  0.580343  0.865760  0.967075  0.894048  1.832835
13  0.760117  0.265385  0.502313  0.774096  0.767698
14  0.843083  0.635828  0.317488  0.042874  0.953316
15  0.766730  0.263869  0.705161  0.242770  0.969030
16  0.222220  0.229465  0.177108  0.941769  0.406573
17  0.825229  0.470504  0.216519  0.914694  0.687023
18  0.761745  0.356599  0.806759  0.743189  1.163358
19  0.922617  0.477434  0.897377  0.511959  1.374811
20  0.001975  0.502431  0.166829  0.125512  0.669260
21  0.836974  0.847921  0.773648  0.689553  1.621569
22  0.991447  0.461161  0.914051  0.608499  1.375212
23  0.448993  0.646557  0.308037  0.948134  0.954594
24  0.012724  0.666883  0.541361  0.237506  1.208243
25  0.829838  0.962669  0.163872  0.430188  1.126541
26  0.817607  0.733099  0.389853  0.055736  1.122952
27  0.413990  0.335205  0.696372  0.537457  1.031577
28  0.449147  0.712366  0.837584  0.865491  1.549950
29  0.882496  0.726720  0.159526  0.165009  0.886246
30  0.767419  0.499641  0.312184  0.809598  0.811826
31  0.890904  0.497236  0.402776  0.740486  0.900012
32  0.660386  0.415972  0.897048  0.586005  1.313020
33  0.703361  0.295038  0.254929  0.441209  0.549967
34  0.652174  0.161277  0.762802  0.910206  0.924079
35  0.255551  0.369938  0.018456  0.467304  0.388394
36  0.135217  0.054327  0.849746  0.887221  0.904073
37  0.330568  0.001420  0.223759  0.694910  0.225180
38  0.155786  0.215030  0.330776  0.171014  0.545806
39  0.583149  0.618692  0.159309  0.885062  0.778001
40  0.072486  0.597401  0.582325  0.218382  1.179726
41  0.127474  0.739164  0.506288  0.764206  1.245452
42  0.725750  0.816711  0.205093  0.950634  1.021804
43  0.222784  0.530855  0.995143  0.618674  1.525998
44  0.332305  0.356187  0.800483  0.244643  1.156671
45  0.008958  0.131560  0.501106  0.597667  0.632666
46  0.995970  0.616158  0.975938  0.058336  1.592096
47  0.625642  0.742597  0.183395  0.398057  0.925992
48  0.533047  0.562315  0.951345  0.028779  1.513660
49  0.136809  0.679218  0.752385  0.552021  1.431603
50  0.824284  0.970517  0.063607  0.056930  1.034124
51  0.401758  0.963311  0.043783  0.081545  1.007095
52  0.405278  0.010577  0.783277  0.832287  0.793854
53  0.030920  0.608325  0.562303  0.691980  1.170628
54  0.531890  0.432852  0.323168  0.026014  0.756021
55  0.591129  0.752152  0.144067  0.975281  0.896219
56  0.347152  0.787107  0.571696  0.441340  1.358803
57  0.944629  0.411152  0.880483  0.176047  1.291635
58  0.469072  0.678394  0.017266  0.461286  0.695660
59  0.207766  0.113678  0.666941  0.359070  0.780619

In [13]:
dataFrame.drop('Sum(X+Y)', axis=1, inplace=True)
dataFrame

W         X         Y         Z
0   0.053658  0.891749  0.136886  0.676516
1   0.517299  0.730383  0.950864  0.833559
2   0.736789  0.144842  0.869749  0.368362
3   0.253387  0.960268  0.298020  0.731131
4   0.474302  0.995580  0.263277  0.260873
5   0.843857  0.241197  0.756605  0.845783
6   0.156269  0.260637  0.340815  0.907928
7   0.082069  0.062995  0.733348  0.920766
8   0.865808  0.278034  0.640922  0.905490
9   0.344353  0.884663  0.309399  0.990720
10  0.651813  0.704361  0.078532  0.574190
11  0.485596  0.360519  0.553330  0.578550
12  0.580343  0.865760  0.967075  0.894048
13  0.760117  0.265385  0.502313  0.774096
14  0.843083  0.635828  0.317488  0.042874
15  0.766730  0.263869  0.705161  0.242770
16  0.222220  0.229465  0.177108  0.941769
17  0.825229  0.470504  0.216519  0.914694
18  0.761745  0.356599  0.806759  0.743189
19  0.922617  0.477434  0.897377  0.511959
20  0.001975  0.502431  0.166829  0.125512
21  0.836974  0.847921  0.773648  0.689553
22  0.991447  0.461161  0.914051  0.608499
23  0.448993  0.646557  0.308037  0.948134
24  0.012724  0.666883  0.541361  0.237506
25  0.829838  0.962669  0.163872  0.430188
26  0.817607  0.733099  0.389853  0.055736
27  0.413990  0.335205  0.696372  0.537457
28  0.449147  0.712366  0.837584  0.865491
29  0.882496  0.726720  0.159526  0.165009
30  0.767419  0.499641  0.312184  0.809598
31  0.890904  0.497236  0.402776  0.740486
32  0.660386  0.415972  0.897048  0.586005
33  0.703361  0.295038  0.254929  0.441209
34  0.652174  0.161277  0.762802  0.910206
35  0.255551  0.369938  0.018456  0.467304
36  0.135217  0.054327  0.849746  0.887221
37  0.330568  0.001420  0.223759  0.694910
38  0.155786  0.215030  0.330776  0.171014
39  0.583149  0.618692  0.159309  0.885062
40  0.072486  0.597401  0.582325  0.218382
41  0.127474  0.739164  0.506288  0.764206
42  0.725750  0.816711  0.205093  0.950634
43  0.222784  0.530855  0.995143  0.618674
44  0.332305  0.356187  0.800483  0.244643
45  0.008958  0.131560  0.501106  0.597667
46  0.995970  0.616158  0.975938  0.058336
47  0.625642  0.742597  0.183395  0.398057
48  0.533047  0.562315  0.951345  0.028779
49  0.136809  0.679218  0.752385  0.552021
50  0.824284  0.970517  0.063607  0.056930
51  0.401758  0.963311  0.043783  0.081545
52  0.405278  0.010577  0.783277  0.832287
53  0.030920  0.608325  0.562303  0.691980
54  0.531890  0.432852  0.323168  0.026014
55  0.591129  0.752152  0.144067  0.975281
56  0.347152  0.787107  0.571696  0.441340
57  0.944629  0.411152  0.880483  0.176047
58  0.469072  0.678394  0.017266  0.461286
59  0.207766  0.113678  0.666941  0.359070

In [15]:
import numpy as np
import pandas as pd

titanicDf = pd.read_csv('Titanic-Dataset.csv')
titanicDf.head() #First 5 rows only

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [16]:
titanicDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
titanicDf.drop('Cabin', axis=1, inplace=True)
titanicDf.drop('Embarked', axis=1, inplace=True)
titanicDf.drop('PassengerID', axis=1, inplace=True)
titanicDf.info()

In [ ]:
titanicDf[titanicDf['Age'].isnull()]

# Cleaning Data

In [ ]:
indexAge = titanicDf[titanicDf['Age'].isnull()]
titanicDf.drop(indexAge, inplace=True)
titanicDf.info()

In [ ]:
titanicDf.replace('male', 0, inplace=True)
titanicDf.replace('female', 1, inplace=True)
titanicDf.info()